# Generated by Django 4.1.6 on 2023-02-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_rename_account_type_ledgermodel_ledger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_type',
            field=models.CharField(choices=[('COMMON', 'Common'), ('SPECIAL', 'Special')], default='COMMON', max_length=12),
        ),
    ]
